
ALTER SESSION SET CONTAINER = FREEPDB1;

BEGIN
EXECUTE IMMEDIATE 'DROP USER sa CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
END IF;
END;
/

CREATE USER sa IDENTIFIED BY sa;

GRANT CONNECT, RESOURCE, DBA TO sa;
GRANT CREATE SESSION TO sa;
GRANT UNLIMITED TABLESPACE TO sa;

ALTER USER sa ACCOUNT UNLOCK;

COMMIT;