services:
  online_survey:
    container_name: 'sa-api'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '8080:8080'
    volumes:
      # Format: HOST_PATH:CONTAINER_PATH
      - '/home/media:/home/media'
      - '/home/keys:/keys'